config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :stories
  resources :votes

  root "stories#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user
	has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def new
		@story = Story.new
	end

	def create
		@story = Story.new params[:story].permit(:name, :string, :body, :text)
		@story.user = current_user
		if @story.save
			redirect_to story_path(@story)
		else
			redirect_to new_story_path
		end
	end

	def index
		@stories = Story.all
	end

	def show
		@story = Story.find(params[:id])
	end

	def edit
		@story = current_user.stories.find(params[:id])
	end

	def update
		@story = current_user.stories.find(params[:id])
		if @story.update params[:story].permit(:name, :string, :body, :text)
			redirect_to story_path(@story)
		else
			redirect_to edit_story_path(@story)
		end
	end

	def destroy
		@story = current_user.stories.find(params[:id])
		@story.destroy
		redirect_to '/stories'
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def new
		# @story = stories.find(params[:id])
		@vote = Vote.new
	end

	def create
		# @story = stories.find(params[:id])
		@vote = Vote.new(params[:vote].permit(:integer))
		@vote.story_id = @story.id
		@vote.user = current_user

		@vote.save
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storiesbase</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%- unless %w(sessions registrations).include?(controller_name) %>
	  <% if user_signed_in? %>
	    <%= current_user.email %>
	    //
	    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
	  <% else %>
	    <%= link_to 'Sign in', new_user_session_path %>
	    //
	    <%= link_to 'Sign up for this awesome site', new_user_registration_path %>
	  <% end %>
  <% end %>


<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story do |x| %>
  
  <%= x.label :name %>
  <%= x.text_field :name %>
  <br>
  <%= x.label :body %>
  <%= x.text_area :body %>
  <br>
  <%= x.submit 'Submit' %>

<% end %>

app/views/stories/edit.html.erb
<%= render 'form' %>

<br>
<%= link_to 'Delete This Story', story_path(@story), :method => :delete %>

app/views/stories/index.html.erb
<h1>Welcome to the stories index</h1>
<%= link_to 'Add a new story here', new_story_path %>
<br>
<br>
<hr>
<% @stories.each do |story| %>
	<strong><%= link_to story.name, story_path(story)%></strong>
	<br>
	<%= truncate(story.body, length: 70) %><br>
	<small>Created by <%= story.user.email %></small>
	<br>
	<%= link_to 'Upvote', new_vote_path %>
	<br>
	<hr>
<% end %>

app/views/stories/new.html.erb
Please write your awesome story below

<%= render 'form' %>

app/views/stories/show.html.erb
Thanks for submitting the below
<br><br>
<h1><%= @story.name %></h1>
<p><%= @story.body %></p>

<% if @story.user == current_user %>
  <%= link_to 'Edit This Story', edit_story_path(@story) %>
  //
  <%= link_to 'Delete This Story', story_path(@story), :method => :delete %>
<% else %>
  Story created by <%= @story.user.email %>
<% end %>
<br>
<%= link_to 'Back to all Stories', stories_path %>